import { GeneratedImage } from "../types/image";
import {getHistoricalDataFromStorage} from "../localstorage/store";

const History: React.FC = () => {
    const generatedImages = getHistoricalDataFromStorage();

    return (
        <div>
            <h2>Historical Data</h2>
            {generatedImages.length > 0 ? (
                <ul>
                    {generatedImages.map((generatedImage: GeneratedImage, index: number) => (
                        <li key={index}>
                            <p>Prompt: {generatedImage.prompt}</p>
                            <img width={250} src={generatedImage.url} alt={`Generated by OpenAI ${index}`} />
                        </li>
                    ))}
                </ul>
            ) : (
                <p>No historical data available.</p>
            )}
        </div>
    );
}

export default History;
